name: Build
on:
  push:
    branches:    
      - master 
  pull_request:
    branches:    
      - master   
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["10", "12"]
    name: Node ${{ matrix.node }} build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Installing
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: UnitTesting
        run: npm run test
      - name: Build
        run: npm run build